---
title: "Meerkat Offspring Final Code"
author: "Caroline L Shearer"
date: "8/20/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(glmmTMB)
```

IMPORT 1-6 MO OFFSPRING AGGR DATA FROM CSV
```{r}
modeldata2 = read.csv("Offspring_dataset_a.csv", header=T, na.strings=c(""," ","NA","na"))
```

AGGRESSION MAM
```{r}
#MAM
week.lit.gs.aggr1to6.off31<-glmmTMB(i.aggr.all ~ X3.way+age.months.cont+group.size+Total.monthly.rainfall+sex+location1+am.pm+group.size*Total.monthly.rainfall+X3.way*age.months.cont+offset(log(obs.time.hr+1))+(1 | mom.id/litter/kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2)

summary(week.lit.gs.aggr1to6.off31)

#BELOW IS THE MAM ACCORDING TO AIC
week.lit.gs.aggr1to6.off32<-glmmTMB(i.aggr.all ~ X3.way+age.months.cont+group.size+Total.monthly.rainfall+location1+am.pm+group.size*Total.monthly.rainfall+X3.way*age.months.cont+offset(log(obs.time.hr+1))+(1|mom.id/litter/kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2, na.action=na.exclude)

summary(week.lit.gs.aggr1to6.off32)

library(car)
Anova(week.lit.gs.aggr1to6.off32)

week.lit.gs.aggr1to6.off33<-glmmTMB(i.aggr.all ~ X3.way+age.months.cont+group.size+Total.monthly.rainfall+location1+ am.pm+X3.way*age.months.cont+offset(log(obs.time.hr+1))+(1 |kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2, na.action=na.exclude)

summary(week.lit.gs.aggr1to6.off33)

week.lit.gs.aggr1to6.off34<-glmmTMB(i.aggr.all ~ X3.way+age.months.cont+group.size+location1+ am.pm+X3.way*age.months.cont+offset(log(obs.time.hr+1))+(1 |litter/kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2, na.action=na.exclude)

summary(week.lit.gs.aggr1to6.off34)

week.lit.gs.aggr1to6.off35<-glmmTMB(i.aggr.all ~ X3.way+age.months.cont+location1+ am.pm+X3.way*age.months.cont+offset(log(obs.time.hr+1))+(1 |mom.id/litter/kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2, na.action=na.exclude)

summary(week.lit.gs.aggr1to6.off35)

library(bbmle)
AICtab(week.lit.gs.aggr1to6.off31,week.lit.gs.aggr1to6.off32,week.lit.gs.aggr1to6.off33,week.lit.gs.aggr1to6.off34,week.lit.gs.aggr1to6.off35)
```

FORWARD STEPWISE PROCEDURE
```{r}

fstep1<-glmmTMB(i.aggr.all ~ 1+offset(log(obs.time.hr+1))+(1 | mom.id/litter/kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2, na.action=na.exclude)
summary(fstep1)

fstep2<-glmmTMB(i.aggr.all ~ location1 + offset(log(obs.time.hr+1))+(1 | mom.id/litter/kmp.id.nospace),zi=~1, data=modeldata2,family=nbinom2, na.action=na.exclude)
summary(fstep2)

fstep3<-glmmTMB(i.aggr.all ~ age.months.cont+location1+offset(log(obs.time.hr+1))+(1 | mom.id/litter/kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2, na.action=na.exclude)
summary(fstep3)

fstep4<-glmmTMB(i.aggr.all ~ age.months.cont+location1+am.pm+offset(log(obs.time.hr+1))+(1 |litter/kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2, na.action=na.exclude)
summary(fstep4)

#cant converge with all random eff
fstep5<-glmmTMB(i.aggr.all ~ X3.way+age.months.cont+location1+am.pm+offset(log(obs.time.hr+1))+(1 | litter/kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2, na.action=na.exclude)
summary(fstep5)

#cant converge with all random eff
fstep6<-glmmTMB(i.aggr.all ~ X3.way+ age.months.cont+ location1+ am.pm + X3.way*age.months.cont+ offset(log(obs.time.hr+1))+(1 | litter/kmp.id.nospace),zi=~1,data=modeldata2,family=nbinom2, na.action=na.exclude)
summary(fstep6)

fstep7<-glmmTMB(i.aggr.all ~ X3.way+age.months.cont+group.size+location1+ am.pm+X3.way*age.months.cont+offset(log(obs.time.hr+1))+(1 | mom.id/litter/kmp.id.nospace),zi=~1, data=modeldata2,family=nbinom2, na.action=na.exclude)
summary(fstep7)

fstep8<-glmmTMB(i.aggr.all ~ X3.way+age.months.cont+group.size+Total.monthly.rainfall+location1+ am.pm+X3.way*age.months.cont+offset(log(obs.time.hr+1))+(1 | mom.id/litter/kmp.id.nospace), zi=~1, data=modeldata2,family=nbinom2, na.action=na.exclude)
summary(fstep8)

fstep9<-glmmTMB(i.aggr.all ~ X3.way+age.months.cont+group.size+Total.monthly.rainfall+location1+ am.pm+X3.way*age.months.cont+group.size*Total.monthly.rainfall+offset(log(obs.time.hr+1))+(1 | mom.id/litter/kmp.id.nospace), zi=~1, data=modeldata2,family=nbinom2, na.action=na.exclude)
summary(fstep9)

AICtab(fstep1,fstep2,fstep3,fstep4,fstep5,fstep6,fstep7,fstep8,fstep9)
```

test for significance likelihood ratio test with x2 distribution
```{r}
library(car)
 Anova(week.lit.gs.aggr1to6.off32) # assesing significance
```

pairwise differences
```{r}
 library(lsmeans)
 ph <- lsmeans(week.lit.gs.aggr1to6.off32, ~ X3.way| age.months.cont)
 summary(as.glht(pairs(ph), by = NULL)) # sig for each pairwise compar.; p-value adjusts, accounting for mult. tests
 plot(ph)
```

SUMMARY INFO ABOUT DATA
```{r}
#sex individ count DT
modeldata2.DT.sex<- modeldata2[ which(modeldata2$X3.way%in%c('Dominant treated') ), ]
modeldata2.DT.F<- modeldata2.DT.sex[ which(modeldata2.DT.sex$sex%in%c('F') ), ]
length(unique(modeldata2.DT.F$kmp.id.nospace))
modeldata2.DT.M<- modeldata2.DT.sex[ which(modeldata2.DT.sex$sex%in%c('M') ), ]
length(unique(modeldata2.DT.M$kmp.id.nospace))
modeldata2.DT.unk<- modeldata2.DT.sex[ which(modeldata2.DT.sex$sex%in%c('unk') ), ]
length(unique(modeldata2.DT.unk$kmp.id.nospace))

#hours
sum(modeldata2.DT.sex$obs.time.hr)
sum(modeldata2$obs.time.hr)

length(unique(modeldata2$kmp.id.nospace))
length(unique(modeldata2$mom.id))
length(unique(modeldata2$litter))
table(modeldata2$age.months)
table(modeldata2$X3.way)
table(modeldata2$age.months,modeldata2$X3.way)
table(modeldata2$X3.way,modeldata2$location1)
table(modeldata2$location1)

table(modeldata2$X3.way,modeldata2$am.pm)
table(modeldata2$am.pm)
table(modeldata2$kmp.id.nospace,modeldata2$X3.way,modeldata2$sex)

mean.time<-mean(modeldata2$obs.time.hr)

60*mean.time

mean.grp.size<-aggregate(modeldata2$group.size, list(modeldata2$X3.way), mean)
mean(modeldata2$group.size)
```

PLOTTING
```{r}
library(ggeffects)
library(ggplot2)
library(sjPlot)
library(prediction)

summary(week.lit.gs.aggr1to6.off32)

momtrtplot2<-ggpredict(week.lit.gs.aggr1to6.off32,c("age.months.cont","X3.way"),full.data=T)
```

B&W FIGURE_rawplot
```{r}
ggplotfig2<-ggplot(momtrtplot2, aes(x, predicted)) + geom_ribbon(aes(ymin=conf.low, ymax=conf.high,fill=group), alpha=0.55)+
    geom_line(aes(linetype=group, color=group),size=1.5) +
     scale_colour_manual(values = c("black", "black", "black"))+labs(x=expression('Offspring age (months)'), y="Predicted aggression initiated",title = "") +set_theme(axis.textcolor.y = "black",axis.textcolor.x = "black", axis.title.color = "black",base = theme_classic()) + theme(text = element_text(size=20,family="Arial",lineheight=unit(2,"line")), legend.position = c(0.75,0.8),legend.key.width=unit(3.5,"line"),legend.key.size = unit(2,"line"),legend.key = element_rect(fill = "white")) +scale_x_continuous(name="Offspring age (months)", breaks=c(1,2,3,4,5,6)) + scale_linetype_manual(values=c("Dominant control"="dashed","Subordinate control"="solid","Dominant treated"="dotted"))+scale_fill_manual(values = c("grey80", "grey45", "grey20"))
ggplotfig2<-update_labels(ggplotfig2, list(fill = "Maternal treatment",linetype = "Maternal treatment",shape = "Maternal treatment",colour = "Maternal treatment"))
ggplotfig2

ggsave(file="figure_2_BW.jpeg",ggplotfig2,width=9,height=8.5,dpi=600)
```

COLOR FIGURE
```{r}
ggplotfig2color2<-ggplot(momtrtplot2, aes(x, predicted)) + geom_ribbon(aes(ymin=conf.low, ymax=conf.high,fill=group), alpha=0.25)+
    geom_line(aes(color=group),size=1.5) +
     scale_colour_manual(values = c("#7570B3", "#E60202", "#FFC107"))+labs(x=expression('Offspring age (months)'), y="Predicted aggression initiated",title = "") +set_theme(axis.textcolor.y = "black",axis.textcolor.x = "black", axis.title.color = "black",base = theme_classic()) + theme(text = element_text(size=20,family="Arial",lineheight=unit(2,"line")), legend.position = c(0.75,0.8),legend.key.width=unit(3.5,"line"),legend.key.size = unit(2,"line"),legend.key = element_rect(fill = "white")) +scale_x_continuous(name="Offspring age (months)", breaks=c(1,2,3,4,5,6)) +scale_fill_manual(values = c("#7570B3", "#E60202", "#FFC107"))
ggplotfig2color2<-update_labels(ggplotfig2color2, list(fill = "Maternal treatment",colour = "Maternal treatment"))
ggplotfig2color2

ggsave(file="figure_2_color.jpeg",ggplotfig2color2,width=9,height=8.5,dpi=600)
```

